//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsRabotaManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employees()
        {
            this.maintable = new HashSet<maintable>();
        }
    
        public int id_employee { get; set; }
        public int id_account { get; set; }
        public string name_employee { get; set; }
        public string surname_employee { get; set; }
        public string middlename_employee { get; set; }
        public System.DateTime birthday_employee { get; set; }
        public bool truemanager_employee { get; set; }
        public string adress_employee { get; set; }
    
        public virtual authorization authorization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maintable> maintable { get; set; }
    }
}
