//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kyrsRabotaManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintable
    {
        public int id { get; set; }
        public int id_order { get; set; }
        public int id_employee { get; set; }
        public bool done { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual orders orders { get; set; }
    }
}
